TravelCup/Controllers/TravelCupClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TravelCup.Data;
using TravelCup.Models;

namespace TravelCup.Controllers
{
    public class TravelCupClassesController : Controller
    {
        private readonly MvcTravelCupContext _context;

        public TravelCupClassesController(MvcTravelCupContext context)
        {
            _context = context;
        }

        // GET: TravelCupClasses
        public async Task<IActionResult> Index(string RechangeSize, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.TravelCupClass
                                            orderby m.Size
                                            select m.Size;

            var cup = from m in _context.TravelCupClass
                         select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                cup = cup.Where(s => s.CupsTitle.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(RechangeSize))
            {
                cup = cup.Where(x => x.Size == RechangeSize);
            }

            var cupReshapeSizeVM = new TravelCupShapeViewModel
            {
                RechangeSize = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Cups = await cup.ToListAsync()
            };

            return View(cupReshapeSizeVM);



        }

        // GET: TravelCupClasses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelCupClass = await _context.TravelCupClass
                .FirstOrDefaultAsync(m => m.Id == id);
            if (travelCupClass == null)
            {
                return NotFound();
            }

            return View(travelCupClass);
        }

        // GET: TravelCupClasses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TravelCupClasses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CupsTitle,ManufactureDate,Shape,Colour,Size,Price,Rating")] TravelCupClass travelCupClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(travelCupClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(travelCupClass);
        }

        // GET: TravelCupClasses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelCupClass = await _context.TravelCupClass.FindAsync(id);
            if (travelCupClass == null)
            {
                return NotFound();
            }
            return View(travelCupClass);
        }

        // POST: TravelCupClasses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CupsTitle,ManufactureDate,Shape,Colour,Size,Price,Rating")] TravelCupClass travelCupClass)
        {
            if (id != travelCupClass.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(travelCupClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TravelCupClassExists(travelCupClass.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(travelCupClass);
        }

        // GET: TravelCupClasses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelCupClass = await _context.TravelCupClass
                .FirstOrDefaultAsync(m => m.Id == id);
            if (travelCupClass == null)
            {
                return NotFound();
            }

            return View(travelCupClass);
        }

        // POST: TravelCupClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var travelCupClass = await _context.TravelCupClass.FindAsync(id);
            _context.TravelCupClass.Remove(travelCupClass);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TravelCupClassExists(int id)
        {
            return _context.TravelCupClass.Any(e => e.Id == id);
        }
    }
}

TravelCup/Views/TravelCupClasses/Create.cshtml
@model TravelCup.Models.TravelCupClass

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TravelCupClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CupsTitle" class="control-label"></label>
                <input asp-for="CupsTitle" class="form-control" />
                <span asp-validation-for="CupsTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufactureDate" class="control-label"></label>
                <input asp-for="ManufactureDate" class="form-control" />
                <span asp-validation-for="ManufactureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shape" class="control-label"></label>
                <input asp-for="Shape" class="form-control" />
                <span asp-validation-for="Shape" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colour" class="control-label"></label>
                <input asp-for="Colour" class="form-control" />
                <span asp-validation-for="Colour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TravelCup/Views/TravelCupClasses/Delete.cshtml
@model TravelCup.Models.TravelCupClass

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TravelCupClass</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CupsTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CupsTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Shape)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Shape)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Colour)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Colour)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TravelCup/Views/TravelCupClasses/Details.cshtml
@model TravelCup.Models.TravelCupClass

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TravelCupClass</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CupsTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CupsTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Shape)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Shape)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Colour)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Colour)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TravelCup/Views/TravelCupClasses/Edit.cshtml
@model TravelCup.Models.TravelCupClass

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TravelCupClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CupsTitle" class="control-label"></label>
                <input asp-for="CupsTitle" class="form-control" />
                <span asp-validation-for="CupsTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufactureDate" class="control-label"></label>
                <input asp-for="ManufactureDate" class="form-control" />
                <span asp-validation-for="ManufactureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shape" class="control-label"></label>
                <input asp-for="Shape" class="form-control" />
                <span asp-validation-for="Shape" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colour" class="control-label"></label>
                <input asp-for="Colour" class="form-control" />
                <span asp-validation-for="Colour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TravelCup/Views/TravelCupClasses/Index.cshtml
@model TravelCup.Models.TravelCupShapeViewModel


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="TravelCupClasses" asp-action="Index">
    <p>
        <select asp-for="RechangeSize" asp-items="Model.RechangeSize">
            <option value="">All</option>
        </select>

        CupsTitle: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cups[0].CupsTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cups[0].ManufactureDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cups[0].Shape)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cups[0].Colour)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cups[0].Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cups[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cups[0].Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cups)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CupsTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufactureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shape)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Colour)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>